-- Textos das perguntas dos sete modelos; IDs e vínculos operacionais são preservados.
UPDATE report_questions question
   SET label = source.label
  FROM (VALUES
    ('M1.13_Q01', 'Descrição dos materiais instrucionais criados no período, como apostilas, vídeos, apresentações e exercícios.'),
    ('M1.13_Q02', 'Relatório sobre os recursos externos que foram selecionados, revisados e utilizados como complemento ao conteúdo desenvolvido internamente.'),
    ('M1.13_Q03', 'Como os materiais estão alinhados com os objetivos pedagógicos de cada capacitação.'),
    ('M1.13_Q04', 'Descrição de quaisquer atualizações ou melhorias realizadas nos materiais previamente existentes.'),
    ('M1.13_Q05', 'Relatório das atividades práticas, estudos de caso, quizzes e exercícios disponibilizados aos estudantes.'),
    ('M1.13_Q06', 'Explicação de como as atividades foram adaptadas para diferentes estilos de aprendizagem.'),
    ('M1.13_Q07', 'Métodos utilizados para aumentar a interação e engajamento dos alunos, como fóruns de discussão e feedback imediato.'),
    ('M1.13_Q08', 'Resumo das respostas dos alunos sobre a eficácia dos materiais e atividades no processo de aprendizagem.'),
    ('M1.13_Q09', 'Análise de como os materiais e atividades estão impactando o desempenho dos estudantes nas avaliações e progressos.'),
    ('M1.13_Q10', 'Relatório de quaisquer dificuldades encontradas na criação ou curadoria dos materiais, como falta de recursos ou necessidade de ajustes nos conteúdos.'),
    ('M1.13_Q11', 'Propostas de melhorias com base nos desafios identificados e no feedback obtido, incluindo ajustes futuros nos materiais ou novas abordagens para as atividades.'),
    ('M1.13_Q12', 'Planejamento para futuras atualizações dos materiais com base em feedbacks e necessidades emergentes.'),
    ('M1.13_Q13', 'Como os materiais instrucionais continuarão sendo revisados e atualizados para manter sua relevância e qualidade ao longo do tempo.'),
    ('M1.13_Q14', 'Sumário das atividades realizadas no mês, impactos observados e próximos passos para o desenvolvimento contínuo de materiais e atividades.'),
    ('M1.13_Q15', 'Exemplos de materiais instrucionais criados, atividades de aprendizagem aplicadas e outros documentos de suporte.'),
    ('M1.14_Q01', 'Descrição dos casos de estudo utilizados, abordando o contexto, objetivos e aplicação prática.'),
    ('M1.14_Q02', 'Exemplos de atividades que envolvem problemas do mundo real, descrevendo o projeto, a metodologia e o impacto no aprendizado.'),
    ('M1.14_Q03', 'Relatório de simulações, experimentos ou outras práticas desenvolvidas para apoiar o processo de ensino.'),
    ('M1.14_Q04', 'Explicação das melhorias realizadas nos objetos de aprendizagem, com base no feedback dos estudantes, tutores ou em novas demandas pedagógicas.'),
    ('M1.14_Q05', 'Descrição de quaisquer mudanças ou inovações no design dos recursos didáticos, como novos formatos ou tecnologias incorporadas.'),
    ('M1.14_Q06', 'Explicação de como os objetos de aprendizagem estão alinhados com as competências e habilidades definidas para cada capacitação.'),
    ('M1.14_Q07', 'Evidências de que os objetos estão cumprindo seus objetivos educacionais, proporcionando aprendizado significativo e aplicado.'),
    ('M1.14_Q08', 'Análise de como o uso dos objetos de aprendizagem impactou o desempenho dos estudantes em avaliações, participação em atividades e engajamento.'),
    ('M1.14_Q09', 'Relatório sobre o feedback dos estudantes em relação aos objetos de aprendizagem, como usabilidade, clareza e aplicabilidade.'),
    ('M1.14_Q10', 'Descrição do processo de revisão e avaliação contínua dos objetos de aprendizagem, identificando oportunidades de melhorias.'),
    ('M1.14_Q11', 'Propostas para aprimoramento contínuo dos recursos e possíveis inclusões de novos objetos de aprendizagem.'),
    ('M1.14_Q12', 'Sumário dos resultados observados e planejamento das ações futuras para a criação, atualização e curadoria dos objetos de aprendizagem.'),
    ('M1.14_Q13', 'Exemplos de objetos de aprendizagem (casos de estudo, simulações, atividades práticas) e documentos que comprovem as melhorias ou inovações aplicadas.'),
    ('M1.15_Q01', 'Detalhes sobre a instalação e configuração do sistema LMS, incluindo servidores, usuários e níveis de acesso.'),
    ('M1.15_Q02', 'Relatório das personalizações feitas no LMS para atender às necessidades específicas do projeto, como integração com outras ferramentas e funcionalidades adicionais.'),
    ('M1.15_Q03', 'Descrição dos testes realizados para garantir que o LMS funcione corretamente para as aulas práticas, tanto síncronas quanto assíncronas.'),
    ('M1.15_Q04', 'Relatório sobre quaisquer problemas técnicos encontrados durante os testes e as soluções implementadas para corrigi-los.'),
    ('M1.15_Q05', 'Relato de simulações com a virtualização de máquinas e o uso de ferramentas técnicas para garantir que as aulas práticas possam ser realizadas remotamente.'),
    ('M1.15_Q06', 'Detalhes sobre a implementação da infraestrutura para a virtualização de máquinas, incluindo a escolha de software, servidores e configuração de ambientes virtuais.'),
    ('M1.15_Q07', 'Relatório sobre os testes realizados para verificar o funcionamento das máquinas virtuais e a interação dos alunos com elas durante as aulas práticas.'),
    ('M1.15_Q08', 'Análise do desempenho do sistema em condições de uso real e sua capacidade de suportar um grande número de usuários simultâneos.'),
    ('M1.15_Q09', 'Descrição das ferramentas e recursos adicionais (como plataformas de videoconferência, sistemas de gestão de tarefas, etc.) que foram integradas ao LMS para otimizar as aulas práticas.'),
    ('M1.15_Q10', 'Explicação de como os recursos técnicos foram preparados para garantir que as atividades práticas possam ser realizadas remotamente, com exemplos de testes e adaptações.'),
    ('M1.15_Q11', 'Relato de feedback dos tutores e alunos que participaram dos testes da infraestrutura e do LMS, destacando a experiência de uso e a efetividade dos recursos técnicos.'),
    ('M1.15_Q12', 'Avaliação da facilidade de uso das ferramentas e da integração dos alunos com o ambiente virtual.'),
    ('M1.15_Q13', 'Descrição de como a infraestrutura tecnológica será monitorada ao longo do tempo, incluindo planos para atualizações e melhorias.'),
    ('M1.15_Q14', 'Plano de ação para realizar ajustes necessários com base no feedback e nos testes realizados.'),
    ('M1.15_Q15', 'Sumário das atividades realizadas até o momento e um cronograma das etapas seguintes para garantir a total funcionalidade e otimização do LMS e dos recursos técnicos.'),
    ('M1.15_Q16', 'Capturas de tela, logs de testes, e relatórios detalhados sobre os testes realizados e os ajustes feitos no LMS e na virtualização de máquinas.'),
    ('M2.1_Q01', 'Explicação sobre o propósito do relatório, que é documentar e comprovar a execução do processo seletivo para as capacitações ofertadas.'),
    ('M2.1_Q02', 'Detalhamento das fases do processo seletivo, como inscrição, triagem, testes, entrevistas, entre outros.'),
    ('M2.1_Q03', 'Apresentação dos critérios usados para avaliar e selecionar os candidatos, conforme definido no relatório de critérios de seleção.'),
    ('M2.1_Q04', 'Quantidade total de candidatos que se inscreveram para as capacitações.'),
    ('M2.1_Q05', 'Análise do perfil dos inscritos, incluindo informações como formação acadêmica, experiências profissionais, e áreas de interesse.'),
    ('M2.1_Q06', 'Relação dos candidatos aprovados, com destaque para aqueles que foram selecionados em primeira chamada e os que estão em lista de espera.'),
    ('M2.1_Q07', 'Percentual de aprovação, taxa de desistência, e outros dados relevantes.'),
    ('M2.1_Q08', 'Descrição das ferramentas e métodos utilizados para avaliar os candidatos.'),
    ('M2.1_Q09', 'Critérios específicos de avaliação e notas médias dos candidatos aprovados.'),
    ('M2.1_Q10', 'Descrição de quaisquer desafios ou problemas enfrentados durante o processo seletivo.'),
    ('M2.1_Q11', 'Soluções aplicadas para resolver os problemas identificados.'),
    ('M2.1_Q12', 'Detalhamento das decisões tomadas em cada fase do processo e a documentação correspondente.'),
    ('M2.1_Q13', 'Resumo final destacando o sucesso do processo seletivo e a conformidade com os critérios estabelecidos, garantindo a transparência e a eficácia na seleção dos candidatos.'),
    ('M2.2_Q01', 'Informações sobre os cursos ou módulos oferecidos, incluindo os objetivos de aprendizagem, ementas, e conteúdos abordados.'),
    ('M2.2_Q02', 'Apresentação das datas e horários das sessões, incluindo a carga horária total e a distribuição das atividades ao longo do curso.'),
    ('M2.2_Q03', 'Quantidade total de participantes que se matricularam nas capacitações.'),
    ('M2.2_Q04', 'Dados sobre a presença dos participantes nas aulas e o nível de engajamento em atividades práticas e teóricas.'),
    ('M2.2_Q05', 'Descrição das plataformas (como LMS) e ferramentas tecnológicas utilizadas para ministrar as capacitações, tanto para o formato presencial quanto remoto.'),
    ('M2.2_Q06', 'Lista de materiais instrucionais utilizados, como apostilas, vídeos, slides, e atividades interativas.'),
    ('M2.2_Q07', 'Detalhamento das metodologias e abordagens pedagógicas utilizadas, como aprendizagem ativa, estudos de caso, e trabalho em grupo.'),
    ('M2.2_Q08', 'Quaisquer ajustes feitos para atender a necessidades específicas dos participantes ou para melhorar a eficácia do ensino.'),
    ('M2.2_Q09', 'Informações sobre as avaliações realizadas, como testes, trabalhos, e feedback dos tutores, incluindo o desempenho médio dos participantes.'),
    ('M2.2_Q10', 'Relatórios sobre a evolução dos participantes ao longo das capacitações, destacando conquistas e áreas que precisam de melhorias.'),
    ('M2.2_Q11', 'Descrição dos principais desafios enfrentados durante a execução das capacitações, como dificuldades técnicas, baixa adesão, ou problemas de comunicação.'),
    ('M2.2_Q12', 'Medidas implementadas para superar os desafios e garantir o andamento bem-sucedido das capacitações.'),
    ('M2.2_Q13', 'Resumo das opiniões dos participantes sobre a qualidade das capacitações, abordagens pedagógicas, e suporte oferecido.'),
    ('M2.2_Q14', 'Recomendações dos participantes e da equipe pedagógica para futuros ciclos de capacitação.'),
    ('M2.2_Q15', 'Dados sobre a taxa de conclusão, satisfação dos participantes, e o impacto das capacitações na formação profissional dos participantes.'),
    ('M2.2_Q16', 'Exemplos de como as capacitações impactaram positivamente os participantes, incluindo casos de aplicação prática dos conhecimentos adquiridos.'),
    ('M2.2_Q17', 'Resumo dos principais resultados alcançados e das lições aprendidas durante a execução das capacitações.'),
    ('M2.2_Q18', 'Planejamento das próximas etapas, como a continuidade das capacitações, revisões de conteúdo, ou novas ofertas de cursos.'),
    ('M2.2_Q19', 'Material didático utilizado em cada trilha.'),
    ('M2.4_Q01', 'Lista detalhada dos indicadores pedagógicos que foram definidos, como taxas de aprovação, frequência, engajamento, satisfação dos estudantes, entre outros.'),
    ('M2.4_Q02', 'Justificativa para a escolha de cada indicador, explicando como eles contribuem para a avaliação do desempenho pedagógico.'),
    ('M2.4_Q03', 'Identificação das fontes de onde os dados foram coletados, como avaliações, questionários, registros de presença, plataformas de ensino (LMS).'),
    ('M2.4_Q04', 'Descrição das ferramentas e métodos utilizados para coletar e armazenar os dados.'),
    ('M2.4_Q05', 'Indicação dos períodos em que a coleta de dados foi realizada, incluindo frequência.'),
    ('M2.4_Q06', 'Marcação de datas-chave durante o processo de coleta.'),
    ('M2.4_Q07', 'Detalhamento do processo de coleta de dados, desde a definição dos indicadores até o armazenamento das informações.'),
    ('M2.4_Q08', 'Descrição das responsabilidades de cada membro da equipe na coleta e no armazenamento dos dados.'),
    ('M2.4_Q09', 'Informações sobre onde e como os dados foram armazenados, garantindo a segurança e a acessibilidade das informações coletadas.'),
    ('M2.4_Q10', 'Medidas tomadas para assegurar que os dados estejam protegidos contra perda ou acessos não autorizados.'),
    ('M2.4_Q11', 'Procedimentos para validar a precisão e a confiabilidade dos dados coletados.'),
    ('M2.4_Q12', 'Relato de quaisquer problemas encontrados durante a coleta e como foram resolvidos.'),
    ('M2.4_Q13', 'Análise preliminar dos dados coletados para identificar tendências, padrões ou áreas de preocupação.'),
    ('M2.4_Q14', 'Se aplicável, comparação com dados de períodos anteriores para avaliar a evolução.'),
    ('M2.4_Q15', 'Tabela organizada contendo todos os indicadores coletados, com valores específicos, intervalos de coleta, e quaisquer observações relevantes.'),
    ('M2.4_Q16', 'Análise preliminar dos indicadores, sugerindo interpretações dos resultados e possíveis ações futuras.'),
    ('M2.4_Q17', 'Breve resumo dos principais resultados encontrados na coleta dos indicadores.'),
    ('M2.4_Q18', 'Recomendações para melhorar a coleta de dados em ciclos futuros ou ajustes na escolha dos indicadores.'),
    ('M2.4_Q19', 'Explicação sobre como os dados coletados serão utilizados para aprimorar as capacitações ou para outras finalidades pedagógicas.'),
    ('M2.6_Q01', 'Definição clara dos critérios utilizados para a emissão das microcredenciais e certificados, como o cumprimento de módulos específicos, a aprovação em avaliações, ou a conclusão de projetos.'),
    ('M2.6_Q02', 'Descrição dos diferentes tipos de microcredenciais emitidas, caso existam variações dependendo do curso ou nível de capacitação.'),
    ('M2.6_Q03', 'Exemplos de como as microcredenciais e certificados foram projetados, incluindo o formato digital e/ou físico, assinaturas, selos de validação, QR Codes.'),
    ('M2.6_Q04', 'Informação sobre a plataforma ou sistema utilizado para a emissão das microcredenciais e certificados.'),
    ('M2.6_Q05', 'Descrição de como as microcredenciais podem ser verificadas por terceiros (empregadores, instituições educacionais, etc.), incluindo o uso de códigos únicos ou links de verificação online.'),
    ('M2.6_Q06', 'Medidas adotadas para garantir a autenticidade das microcredenciais e certificados emitidos.'),
    ('M2.6_Q07', 'Lista completa dos estudantes que receberam microcredenciais e certificados, incluindo nome, identificação do estudante (como matrícula ou ID), e o curso ou módulo concluído.'),
    ('M2.6_Q08', 'Registro das datas em que as microcredenciais e certificados foram emitidos.'),
    ('M2.6_Q09', 'Descrição das competências e habilidades reconhecidas por cada microcredencial ou certificado emitido.'),
    ('M2.6_Q10', 'Indicação do nível de certificação, caso aplicável (por exemplo, iniciante, intermediário, avançado).'),
    ('M2.6_Q11', 'Explicação de como os estudantes receberam suas microcredenciais e certificados, seja por meio de download direto, e-mail, ou envio físico.'),
    ('M2.6_Q12', 'Orientações fornecidas aos estudantes sobre como acessar e utilizar suas microcredenciais, incluindo integração com perfis online ou redes sociais profissionais.'),
    ('M2.6_Q13', 'Análise de como a emissão de microcredenciais e certificados contribuiu para os objetivos do curso e para o desenvolvimento profissional dos estudantes.'),
    ('M2.6_Q14', 'Coleta e apresentação de feedback dos estudantes sobre a relevância e utilidade das microcredenciais e certificados emitidos.'),
    ('M2.6_Q15', 'Relato de possíveis problemas enfrentados durante o processo de emissão e como foram resolvidos.'),
    ('M2.6_Q16', 'Resumo quantitativo das microcredenciais e certificados emitidos e a taxa de sucesso do processo.'),
    ('M2.6_Q17', 'Inclusão de amostras de certificados emitidos, com todos os elementos de autenticação.'),
    ('M2.6_Q18', 'Gráficos ou tabelas que representem o número de microcredenciais emitidas por curso, data, ou outras categorias relevantes.')
  ) AS source(code, label)
 WHERE question.code = source.code;
